name: 'Parse Arguments'
description: ''
inputs:
  github-token:
    description: 'token'
    required: true
  command-prefix:
    description: 'Prefix of the command.'
    required: true
    default: '/build'
  command-options:
    description: "JSON string of the parseArgs options (https://github.com/pkgjs/parseargs)"
    default: '{ "env": { "type": "string"  }, "refresh-db": { "type": "bool" } }'
outputs: {}
runs:
  using: 'node16'
  main: 'dist/index.js'
